let obj = [
    {
        number: "1599",
        subject: "시설 이용 관련 개선 요청 사항 질문입니다.",
        writer: "김**",
        date: "2024-10-14",
        cnt: 16,
        stat: false,
    },
    {
        number: "1598",
        subject: "영도사업소 테니스네트 교체요청합니다.",
        writer: "서**",
        date: "2024-10-05",
        cnt: 50,
        stat: true,
    },
    {
        number: "1597",
        subject: "남부사업소 남부환경체육공원 농구장 그물 교체바랍니다! 농구장 바...",
        writer: "최**",
        date: "2024-10-01",
        cnt: 17,
        stat: true,
    },
    {
        number: "1596",
        subject: "테니스코트 예약에 대하여...",
        writer: "이**",
        date: "2024-09-23",
        cnt: 78,
        stat: true,
    },
    {
        number: "1595",
        subject: "테니스코트 예약에 대하여...",
        writer: "이**",
        date: "2024-09-23",
        cnt: 78,
        stat: true,
    },
    {
        number: "1594",
        subject: "테니스코트 예약에 대하여...",
        writer: "이**",
        date: "2024-09-23",
        cnt: 78,
        stat: true,
    },
    {
        number: "1593",
        subject: "테니스코트 예약에 대하여...",
        writer: "이**",
        date: "2024-09-23",
        cnt: 78,
        stat: true,
    },
    {
        number: "1592",
        subject: "테니스코트 예약에 대하여...",
        writer: "이**",
        date: "2024-09-23",
        cnt: 78,
        stat: true,
    },
    {
        number: "1591",
        subject: "테니스코트 예약에 대하여...",
        writer: "이**",
        date: "2024-09-23",
        cnt: 78,
        stat: true,
    },
    {
        number: "1590",
        subject: "테니스코트 예약에 대하여...",
        writer: "이**",
        date: "2024-09-23",
        cnt: 78,
        stat: true,
    },
]

let obj2 = [
    {
        number: "1366",
        subject: "부산환경공단 2024년도 하반기 청년 체험형 인턴 채용 공고",
        writer: "이준협",
        download: "",
        date: "2024-10-16",
        cnt: "633"
    },
    {
        number: "1365",
        subject: "부산환경공단 정관사업소 기간제근로자 최종합격자 공고",
        writer: "박진우",
        download: "",
        date: "2024-10-14",
        cnt: "871"
    },
    {
        number: "1364",
        subject: "부산환경공단 관로사업소 기간제근로자(현업보조원) 채용 최종합격...",
        writer: "박진우",
        download: "",
        date: "2024-10-11",
        cnt: "339"
    },
    {
        number: "1363",
        subject: "2024년 하반기 부산환경공단 신규직원 채용 필기시험 공고",
        writer: "김명섭",
        download: "",
        date: "2024-10-11",
        cnt: "560"
    },
    {
        number: "1362",
        subject: "부산환경공단 2024년도 하반기 청년 체험형 인턴 채용 공고",
        writer: "이준협",
        download: "",
        date: "2024-10-16",
        cnt: "633"
    },
    {
        number: "1361",
        subject: "부산환경공단 정관사업소 기간제근로자 최종합격자 공고",
        writer: "박진우",
        download: "",
        date: "2024-10-14",
        cnt: "871"
    },
    {
        number: "1360",
        subject: "부산환경공단 관로사업소 기간제근로자(현업보조원) 채용 최종합격...",
        writer: "박진우",
        download: "",
        date: "2024-10-11",
        cnt: "339"
    },
    {
        number: "1359",
        subject: "2024년 하반기 부산환경공단 신규직원 채용 필기시험 공고",
        writer: "김명섭",
        download: "",
        date: "2024-10-11",
        cnt: "560"
    },
    {
        number: "1358",
        subject: "2024년 하반기 부산환경공단 신규직원 채용 필기시험 공고",
        writer: "김명섭",
        download: "",
        date: "2024-10-11",
        cnt: "560"
    },
    {
        number: "1357",
        subject: "2024년 하반기 부산환경공단 신규직원 채용 필기시험 공고",
        writer: "김명섭",
        download: "",
        date: "2024-10-11",
        cnt: "560"
    },
]

let obj3 = [
    {
        division:"법정기준",
        ph:null,
        bod:10,
        toc:25,
        ss:10,
        t_n:20,
        t_p:2,
    },
    {
        division:"수영사업단",
        ph:null,
        bod:"3.6(2024-10-16)",
        toc:null,
        ss:3.1,
        t_n:6.726,
        t_p:0,
    },
    {
        division:"강변사업단",
        ph:6.2,
        bod:"3.8(2024-10-16)",
        toc:5.2,
        ss:2.0,
        t_n:6.752,
        t_p:0.366,
    },
    {
        division:"남부사업단",
        ph:null,
        bod:"2.8(2024-10-16)",
        toc:null,
        ss:2.2,
        t_n:6.868,
        t_p:0,
    },
    {
        division:"녹산사업단",
        ph:null,
        bod:"1.0(2024-10-16)",
        toc:null,
        ss:1.8,
        t_n:8.279,
        t_p:0,
    },
    {
        division:"해운대사업단",
        ph:null,
        bod:"0.5(2024-10-16)",
        toc:null,
        ss:1.0,
        t_n:5.796,
        t_p:0.241,
    },
    {
        division:"서부사업소",
        ph:7.01,
        bod:"1.0(2024-10-16)",
        toc:null,
        ss:0.9,
        t_n:2.737,
        t_p:0.122,
    },
    {
        division:"중앙사업소",
        ph:null,
        bod:"2.3(2024-10-16)",
        toc:null,
        ss:3.3,
        t_n:6.079,
        t_p:0,
    },
    {
        division:"영도사업소",
        ph:null,
        bod:null,
        toc:null,
        ss:null,
        t_n:null,
        t_p:null,
    },
    {
        division:"기장사업소(기장)",
        ph:null,
        bod:"1.2(2024-10-16)",
        toc:null,
        ss:1.3,
        t_n:7.778,
        t_p:0,
    },
    {
        division:"기장사업소(문오성)",
        ph:null,
        bod:"1.3(2024-10-16)",
        toc:null,
        ss:2.1,
        t_n:6.721,
        t_p:0,
    },
    {
        division:"기장사업소(일광)",
        ph:null,
        bod:null,
        toc:null,
        ss:null,
        t_n:null,
        t_p:null,
    },
]